services:
  ssr:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: ssr
    environment:
      - PASSWORD=password
      - SERVER_PORT=8388
      # - METHOD=chacha20
      # - PROTOCOL=origin
      # - OBFS=http_simple
    ports:
      # format: <host_port>:<container_port>
      # Just change the host_port to the port you want to use
      - "4300:8388"
    restart: unless-stopped
