services:
  ssr:
    image: breakwa11/shadowsocksr
    container_name: ssr
    environment:
      - PASSWORD=password
      - SERVER_PORT=8388
      # - METHOD=chacha20
      # - PROTOCOL=origin
      # - OBFS=http_simple
    ports:
      - "4300:8388"
    restart: always
