services:
  ssr:
    image: breakwa11/shadowsocksr
    container_name: ssr
    environment:
      - PASSWORD=@Abcami6082
      - SERVER_PORT=${SERVER_PORT}
      # - METHOD=chacha20
      # - PROTOCOL=origin
      # - OBFS=http_simple
    ports:
      - "4300:${SERVER_PORT}"
    restart: always
